version: $(core_version)+{branch}.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(core_version)
  assembly_file_version: $(core_version)
  assembly_informational_version: $(core_version)
environment:
  core_version: 1.1.0
nuget:
  disable_publish_on_pr: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: yhmsBOdD4lsEpHfFb/rNXDm90EuL+OBaJuCI7yUzc2fcwS2egdtt/ItGFPYBwZEQ9yz+q5de1YAphBCXxM3lDS5h65lgnHKwKSOKn2BAyKU=
  on:
    branch: master
    appveyor_repo_tag: true
